#!/bin/bash
#
# See usage().

[[ -n $DEBUG ]] && set -x

set -eou pipefail
IFS=$'\n\t'

# We do this so the called script name variable is available in utility functions
# below, in case of name change, brew alias, etc.
SCRIPT=`basename ${BASH_SOURCE[0]}`

usage() {
  cat <<EOF
${SCRIPT}(1)

NAME
    ${SCRIPT} - Quick k8s pod port-forward utility.

REQUIRES
    kubectl(1)

SYNOPSIS
    ${SCRIPT} [OPTIONS]

DESCRIPTION
    ${SCRIPT} is a quick kubernetes (k8s) utility to port-forward a pod to localhost (127.0.0.1). ${SCRIPT} prompts for:
      - <NAMESPACE> (defaults to current ns. See kubens(1))
      - <POD> (defaults to "1")
      - <LOCAL_PORT> (If "-p" or "--port" is envoked, designate an available local port. Defaults to the first exposed port of the pod)
      - <REMOTE_PORT> (If "-p" or "--port" is envoked, select from the list of remote ports to forward.)
    ENTER to use defaults.

OPTIONS
    -h, --help
        Show this help message
    -p, --port
        Port-forwards to a lone port on the remote host

SEE ALSO
    kubectx(1), kubens(1), kex(1)
EOF
}

ns_current() {
  # Borrowed partly from kubens current_namespace().
  cur_ctx=$(kubectl config current-context)
  echo "$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"${cur_ctx}\")].context.namespace}")"
}

ns_param() {
  local ns=$(ns_select)
  if [[ ! -z ${ns:-} ]]; then
    echo "--namespace=${ns}"
  fi
}

ns_list() {
  kubectl get namespaces -o=jsonpath='{range .items[*].metadata.name}{@}{"\n"}{end}'
}

ns_number_list() {
  ns_list | nl
}

ns_select() {
  if [[ ! -z ${NS:-} ]]; then
    ns_list | sed -n ${NS}p
  elif [[ ! -z ${NAMESPACE:-} ]]; then
    echo $NAMESPACE
  else
    ns_current
  fi
}

po_list() {
  kubectl $(ns_param) \
    get pods \
    -o=jsonpath='{range .items[*].metadata.name}{@}{"\n"}{end}'
}

po_number_list() {
  po_list | nl
}

po_select() {
  po_list | sed -n ${POD:-1}p
}

port_list() {
  kubectl get po $(ns_param) $(po_select)\
  -o=jsonpath='{..containerPort}' \
  | tr " " "\n" \
  | sort -u
}

# Because *nix denies binding to ports below 1001, we assign a port of N+50000,
# where `n` is a sub-1001 port. Much better to adhere to the security protocol
# than to manipulate the bash binary.
# See second caveat: https://stackoverflow.com/a/414258/4096495
port_check() {
  if [[ $1 -lt 1001 ]]; then
    echo "$(($1+50000))";
  else
    echo $1;
  fi
}

port_x() {
  for i in $(port_list); do
    echo $(port_check $i)
  done
}

port_number_list() {
  port_list | nl
}

port_sniff() {
  port_list | sed -n ${REMOTE_PORT:-1}p
}

po_pf() {
  LOCAL_CHECK=$(port_check ${LOCAL_PORT:-$(port_sniff)})
  kubectl port-forward \
    $(ns_param) $(po_select) $LOCAL_CHECK:${REMOTE_PORT:-$(port_sniff)}
}

po_pf_all() {
    kubectl port-forward $(ns_param) $(po_select) $(port_x)
}

# Transform long options to short ones. Sick trick.
# http://stackoverflow.com/a/30026641/4096495
for arg in "$@"; do
  shift
  case "$arg" in
    "--help")       set -- "$@" "-h" ;;
    "--port")        set -- "$@" "-p" ;;
    *)              set -- "$@" "$arg"
  esac
done

while getopts :ph OPT; do
  case $OPT in
    h ) HELP=true;;
    p ) PORT=true;;
    \?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
    : ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
  esac
done
shift $((OPTIND-1))

# Help and port-forward should not happen simultaneously, so elif.
if [[ ${HELP:-} == 'true' ]]; then
  usage; exit 0
else
  ns=$(ns_current)
  echo "Namespace? (default ${ns:-default}):"; ns_number_list; read NS;
  echo 'Pod number? (default 1):'; po_number_list; read POD;

  if [[ ${PORT:-} == 'true' ]]; then
    echo 'Remote port number? (default 1):'; port_number_list; read REMOTE_PORT;
    echo "Local port number? (defaults to $(port_sniff)):"; read LOCAL_PORT;
    po_pf
  else
    po_pf_all
  fi
fi
